### ISSUE TITLE
Default should permit more than 5 areas

### ISSUE THREAD

**Issue by davidainman** [derpetermann/sBayes#24]
When trying to plot a map of K=6, I get the following error:

    all_labels = self.visualize_areas(locations_map_crs, extent, cfg_content, cfg_graphic, cfg_legend, ax)
  File "/Users/david/Documents/sbayes/sbayes/plot.py", line 564, in visualize_areas
    current_color = cfg_graphic['areas']['color'][i]
IndexError: tuple index out of range

It appears that the default area colors is capped to 5? This should be expanded as with families so it is dynamically generated.

**Comment by derpetermann** [comment]
fixed.
