### ISSUE TITLE
Model logging should be suppressed when sampling from the prior

### ISSUE THREAD

**Issue by davidainman** [derpetermann/sBayes#29]
When sampling from the prior, there is an error because the obervation_lhs is None. But this is expected when sampling from the prior. So model logs should not be made when sampling from the prior.

**Comment by NicoNeureiter** [comment]
Should be resolved in https://github.com/derpetermann/sBayes/commit/6f5252ce7d932e28d54c3f8b6c5ee7b282d8178d
