### ISSUE TITLE
deprecation warning related to pip 

### ISSUE THREAD

**Issue by nataliacp** [derpetermann/sBayes#33]
During installation I ran into this deprecation warning:
DEPRECATION: sbayes is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Comment by NicoNeureiter** [comment]
Should be resolved on devel by using pyproject.toml f6aa8b604f60ae5cffbc7f5d34a4ab956863f889
