### ISSUE TITLE
Plotting should always generate probability grids, or be a flag in the config file

### ISSUE THREAD

**Issue by davidainman** [derpetermann/sBayes#4]
As done, probability grids have to be requested from within python code, but they should probably be in the config file with a flag for "generate them all" or "generate none." Then you can do more in python if you prefer.

**Comment by davidainman** [comment]
I think this is fixed, since it's in the plot_config.json now. Probably safe to close, although we should make sure it's documented in the manual.

**Comment by davidainman** [comment]
Shouldn't this be resolved now?

**Comment by NicoNeureiter** [comment]
Yes, this has been resolved with the command line interface and the option to configure the plots in the config file.
