### ISSUE TITLE
The mathematical treatment of missing data

### ISSUE THREAD

**Issue by davidainman** [derpetermann/sBayes#6]
Following discussion with Nico, we think there needs to be a decision and justification for how to treat missing data:
(1) as it is treated now, not adding it;
(2) split probability equally across all possible states

**Comment by NicoNeureiter** [comment]
The two options are mathematically equivalent. If you want, we can discuss it sometime, but I think the issue can be closed.

**Comment by davidainman** [comment]
Let's discuss it next meeting, but I recall us not being sure if they were equivalent last time. This could have been a misunderstanding as well.

**Comment by NicoNeureiter** [comment]
We discussed it and agreed that the two options are equivalent
